package databaseAccess;
// Generated 2/set/2017 13:22:44 by Hibernate Tools 4.0.1.Final

/**
 * Expression generated by hbm2java
 */
public class Expression implements java.io.Serializable {

	private Integer id;
	private Genes genes;
	private Sample sample;
	private double expression;
	private Double cfrma;
	private Double quantiled;

	public Expression() {
	}

	public Expression(Genes genes, Sample sample, double expression) {
		this.genes = genes;
		this.sample = sample;
		this.expression = expression;
	}

	public Expression(Genes genes, Sample sample, double expression, Double cfrma, Double quantiled) {
		this.genes = genes;
		this.sample = sample;
		this.expression = expression;
		this.cfrma = cfrma;
		this.quantiled = quantiled;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Genes getGenes() {
		return this.genes;
	}

	public void setGenes(Genes genes) {
		this.genes = genes;
	}

	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	public double getExpression() {
		return this.expression;
	}

	public void setExpression(double expression) {
		this.expression = expression;
	}

	public Double getCfrma() {
		return this.cfrma;
	}

	public void setCfrma(Double cfrma) {
		this.cfrma = cfrma;
	}

	public Double getQuantiled() {
		return this.quantiled;
	}

	public void setQuantiled(Double quantiled) {
		this.quantiled = quantiled;
	}

}
