package databaseAccess;
// Generated 24/jul/2017 17:41:59 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Genes generated by hbm2java
 */
public class Genes implements java.io.Serializable {

	private Integer id;
	private Organisms organisms;
	private int entrez;
	private String genesymbol;
	private Set probeses = new HashSet(0);
	private Set genealiases = new HashSet(0);
	private Set expressions = new HashSet(0);

	public Genes() {
	}

	public Genes(Organisms organisms, int entrez) {
		this.organisms = organisms;
		this.entrez = entrez;
	}

	public Genes(Organisms organisms, int entrez, String genesymbol, Set probeses, Set genealiases, Set expressions) {
		this.organisms = organisms;
		this.entrez = entrez;
		this.genesymbol = genesymbol;
		this.probeses = probeses;
		this.genealiases = genealiases;
		this.expressions = expressions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Organisms getOrganisms() {
		return this.organisms;
	}

	public void setOrganisms(Organisms organisms) {
		this.organisms = organisms;
	}

	public int getEntrez() {
		return this.entrez;
	}

	public void setEntrez(int entrez) {
		this.entrez = entrez;
	}

	public String getGenesymbol() {
		return this.genesymbol;
	}

	public void setGenesymbol(String genesymbol) {
		this.genesymbol = genesymbol;
	}

	public Set getProbeses() {
		return this.probeses;
	}

	public void setProbeses(Set probeses) {
		this.probeses = probeses;
	}

	public Set getGenealiases() {
		return this.genealiases;
	}

	public void setGenealiases(Set genealiases) {
		this.genealiases = genealiases;
	}

	public Set getExpressions() {
		return this.expressions;
	}

	public void setExpressions(Set expressions) {
		this.expressions = expressions;
	}

}
