package databaseAccess;
// Generated 28/mar/2017 18:11:50 by Hibernate Tools 4.0.1.Final

/**
 * Genealias generated by hbm2java
 */
public class Genealias implements java.io.Serializable, Comparable<Genealias> {

	private Integer id;
	private Genes genes;
	private String alias;

	public Genealias() {
	}

	public Genealias(Genes genes, String alias) {
		this.genes = genes;
		this.alias = alias;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Genes getGenes() {
		return this.genes;
	}

	public void setGenes(Genes genes) {
		this.genes = genes;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Override
	public int compareTo(Genealias o) {
		return alias.compareTo(o.getAlias());
	}

}
