package databaseAccess;
// Generated 28/mar/2017 18:11:50 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Keywords generated by hbm2java
 */
public class Keywords implements java.io.Serializable {

	private Integer id;
	private String keyword;
	private Set samplekeywordses = new HashSet(0);
	private Set experimentkeywordses = new HashSet(0);

	public Keywords() {
	}

	public Keywords(String keyword) {
		this.keyword = keyword;
	}

	public Keywords(String keyword, Set samplekeywordses, Set experimentkeywordses) {
		this.keyword = keyword;
		this.samplekeywordses = samplekeywordses;
		this.experimentkeywordses = experimentkeywordses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public Set getSamplekeywordses() {
		return this.samplekeywordses;
	}

	public void setSamplekeywordses(Set samplekeywordses) {
		this.samplekeywordses = samplekeywordses;
	}

	public Set getExperimentkeywordses() {
		return this.experimentkeywordses;
	}

	public void setExperimentkeywordses(Set experimentkeywordses) {
		this.experimentkeywordses = experimentkeywordses;
	}

}
