package databaseAccess;
// Generated 28/mar/2017 18:11:50 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Organisms generated by hbm2java
 */
public class Organisms implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set samples = new HashSet(0);
	private Set geneses = new HashSet(0);

	public Organisms() {
	}

	public Organisms(String name) {
		this.name = name;
	}

	public Organisms(String name, Set samples, Set geneses) {
		this.name = name;
		this.samples = samples;
		this.geneses = geneses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getSamples() {
		return this.samples;
	}

	public void setSamples(Set samples) {
		this.samples = samples;
	}

	public Set getGeneses() {
		return this.geneses;
	}

	public void setGeneses(Set geneses) {
		this.geneses = geneses;
	}

}
