package databaseAccess;
// Generated 28/mar/2017 18:11:50 by Hibernate Tools 4.0.1.Final

/**
 * Probes generated by hbm2java
 */
public class Probes implements java.io.Serializable {

	private Integer id;
	private Genes genes;
	private String probe;
	private String platform;

	public Probes() {
	}

	public Probes(Genes genes, String probe) {
		this.genes = genes;
		this.probe = probe;
	}

	public Probes(Genes genes, String probe, String platform) {
		this.genes = genes;
		this.probe = probe;
		this.platform = platform;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Genes getGenes() {
		return this.genes;
	}

	public void setGenes(Genes genes) {
		this.genes = genes;
	}

	public String getProbe() {
		return this.probe;
	}

	public void setProbe(String probe) {
		this.probe = probe;
	}

	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

}
