package databaseAccess;
// Generated 28/mar/2017 18:11:50 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sampletime generated by hbm2java
 */
public class Sampletime implements java.io.Serializable {

	private Integer id;
	private String time;
	private Set samples = new HashSet(0);

	public Sampletime() {
	}

	public Sampletime(String time) {
		this.time = time;
	}

	public Sampletime(String time, Set samples) {
		this.time = time;
		this.samples = samples;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Set getSamples() {
		return this.samples;
	}

	public void setSamples(Set samples) {
		this.samples = samples;
	}

}
