package databaseAccess;
// Generated 11/abr/2017 10:20:55 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sampletype generated by hbm2java
 */
public class Sampletype implements java.io.Serializable, Comparable<Sampletype> {

	private Integer id;
	private Supertype supertype;
	private String type;
	private String class_;
	private Set samples = new HashSet(0);

	public Sampletype() {
	}

	public Sampletype(String type) {
		this.type = type;
	}

	public Sampletype(Supertype supertype, String type, String class_, Set samples) {
		this.supertype = supertype;
		this.type = type;
		this.class_ = class_;
		this.samples = samples;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Supertype getSupertype() {
		return this.supertype;
	}

	public void setSupertype(Supertype supertype) {
		this.supertype = supertype;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public Set getSamples() {
		return this.samples;
	}

	public void setSamples(Set samples) {
		this.samples = samples;
	}
	
	@Override
	public int compareTo(Sampletype o) {
		return this.type.compareTo(o.getType());
	}

}
