package databaseAccess;
// Generated 28/mar/2017 18:11:50 by Hibernate Tools 4.0.1.Final

/**
 * Samplekeywords generated by hbm2java
 */
public class Samplekeywords implements java.io.Serializable {

	private Integer id;
	private Keywords keywords;
	private Sample sample;
	private boolean curated;

	public Samplekeywords() {
	}

	public Samplekeywords(Keywords keywords, Sample sample, boolean curated) {
		this.keywords = keywords;
		this.sample = sample;
		this.curated = curated;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Keywords getKeywords() {
		return this.keywords;
	}

	public void setKeywords(Keywords keywords) {
		this.keywords = keywords;
	}

	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	public boolean isCurated() {
		return this.curated;
	}

	public void setCurated(boolean curated) {
		this.curated = curated;
	}

}
