package databaseAccess;
// Generated 11/abr/2017 10:20:55 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Supertype generated by hbm2java
 */
public class Supertype implements java.io.Serializable, Comparable<Supertype> {

	private Integer id;
	private String supertype;
	private Set sampletypes = new HashSet(0);

	public Supertype() {
	}

	public Supertype(String supertype) {
		this.supertype = supertype;
	}

	public Supertype(String supertype, Set sampletypes) {
		this.supertype = supertype;
		this.sampletypes = sampletypes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSupertype() {
		return this.supertype;
	}

	public void setSupertype(String supertype) {
		this.supertype = supertype;
	}

	public Set getSampletypes() {
		return this.sampletypes;
	}

	public void setSampletypes(Set sampletypes) {
		this.sampletypes = sampletypes;
	}

	@Override
	public int compareTo(Supertype o) {
		return this.supertype.compareTo(o.getSupertype());
	}

}
